global:
  scrape_interval: 15s
  external_labels: {}

scrape_configs:
  - job_name: ovh-exporter
    scrape_interval: 1m
    scrape_timeout: 40s
    static_configs:
    - targets:
      - localhost:9100
