version: '2.1'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
    - ./prometheus:/etc/prometheus
    - prometheus-data:/prometheus
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--enable-feature=exemplar-storage'
    # expose:
    # - 9090
    # ports:
    # - "9090:9090"
    network_mode: host
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    volumes:
    - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
    - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
    - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    - GF_USERS_ALLOW_SIGN_UP=false
    - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource
    # ports:
    # - 3000:3000
    network_mode: host

volumes:
  prometheus-data: {}
