{
 "title": "OVH exporter",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "kobalt_client", "label": "Client", "query": { "query": "label_values(kobalt_client)" } }
  ]
 },
 "panels": [
  {
   "title": "Coûts totaux",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum({__name__=~\"ovh_usage_instance_price|ovh_usage_volume_price|ovh_usage_storage_price|ovh_usage_storage_bandwidth_external_incoming_price|ovh_usage_storage_bandwidth_external_outgoing_price|ovh_usage_storage_bandwidth_internal_incoming_price|ovh_usage_storage_bandwidth_internal_outgoing_price\"}) by (kobalt_client)",
     "legendFormat": "{{kobalt_cliient}}"
    }
   ]
  },
  {
   "title": "Prix",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum(ovh_usage_storage_price{kobalt_client=\"$kobalt_client\"})",
     "legendFormat": "Object storage"
    },
    {
     "expr": "sum(ovh_usage_volume_price{kobalt_client=\"$kobalt_client\"})",
     "legendFormat": "Volumes"
    },
    {
     "expr": "sum(ovh_usage_instance_price{kobalt_client=\"$kobalt_client\",type=\"monthly\"})",
     "legendFormat": "Instances (mensuel)"
    },
    {
     "expr": "sum(ovh_usage_instance_price{kobalt_client=\"$kobalt_client\",type=\"hourly\"})",
     "legendFormat": "Instances (horaire)"
    },
    {
     "expr": "sum(ovh_usage_storage_bandwidth_external_incoming_price{kobalt_client=\"$kobalt_client\"} + ovh_usage_storage_bandwidth_internal_incoming_price{kobalt_client=\"$kobalt_client\"})",
     "legendFormat": "Object storage / incoming bandwidth"
    },
    {
     "expr": "sum(ovh_usage_storage_bandwidth_external_outgoing_price{kobalt_client=\"$kobalt_client\"} + ovh_usage_storage_bandwidth_internal_outgoing_price{kobalt_client=\"$kobalt_client\"})",
     "legendFormat": "Object storage / outgoing bandwidth"
    }
   ]
  },
  {
   "title": "Volume / Object storage size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(ovh_quota_volume_gb{kobalt_client=\"$kobalt_client\"}) * 1000000000",
     "legendFormat": "Volumes"
    },
    {
     "expr": "sum(ovh_storage_size_bytes{kobalt_client=\"$kobalt_client\"})",
     "legendFormat": "Object storage"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ovh_quota_instance_count{kobalt_client=\"$kobalt_client\"})",
     "legendFormat": "Instances count"
    },
    {
     "expr": "sum(ovh_quota_cpu_count{kobalt_client=\"$kobalt_client\"})",
     "legendFormat": "CPU count"
    },
    {
     "expr": "sum(ovh_quota_cpu_max_count{kobalt_client=\"$kobalt_client\"})",
     "legendFormat": "Max CPU count"
    },
    {
     "expr": "sum(ovh_quota_instance_max_count{kobalt_client=\"$kobalt_client\"})",
     "legendFormat": "Max instances count"
    },
    {
     "expr": "sum(ovh_quota_volume_count{kobalt_client=\"$kobalt_client\"})",
     "legendFormat": "Volumes count"
    }
   ]
  }
 ]
}