name: Build

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build
      run: |
        apt-get update && apt-get install -y pipx
        pipx install hatch
        alias hatch=~/.local/bin/hatch
        hatch fmt --check
        hatch run types:check
        hatch run test
        hatch build
